bump_version: null
nf_core_version: 3.0.2
org_path: null
repository_type: pipeline

template:
  author: Olga Botvinnik
  description: Search for matching protein sequences using k-mers
  force: false
  is_nfcore: true
  name: kmerseek
  org: nf-core
  outdir: .
  skip_features: null
  version: 1.0dev
update: null

lint:
  files_unchanged:
    - docs/images/nf-core-kmerseek_logo_dark.png